### ISSUE TITLE
Run mix format?

### ISSUE THREAD

**Issue by fhunleth** [zeam-vm/pelemay#12]
Could you add a `.formatter.exs` and run `mix format`? I realize this is a trivial request, but it would make it easier to send clean PRs up. There are just enough minor changes that the formatter makes that I did not feel comfortable sending the PR up myself.

**Comment by hisaway** [comment]
I didn't know that!
I feel that need to study about mix and GitHub.

> but it would make it easier to send clean PRs up.

Thank @fhunleth for the useful information.
