### ISSUE TITLE
/usr/include doesn't exist in Catalina

### ISSUE THREAD

**Issue by zacky1972** [zeam-vm/pelemay#136]
**Describe the bug**
Pelemay can't `mix compile` in case of `CC=gcc` because `/usr/include` doesn't exist in Catalina.

**To Reproduce**
1. Use Pelemay in some source code
2. set `export CC=gcc`
3. Run in the command 'mix compile'
4. See error:

```c
.../erl_drv_nif.h:158:12: fatal error: sys/types.h: No such file or directory
  158 | #  include <sys/types.h>
      |            ^~~~~~~~~~~~~
compilation terminated.
```

**Expected behavior**

Makefile should be added the following in case of macOS:

```make
  `CFLAGS += -I`xcrun --show-sdk-path`/usr/include
```

**Screenshots**
None.

**Desktop (please complete the following information):**

In case of Catalina

**Additional context**
None.

**Comment by atomsand** [comment]
Hi, sorry to interrupt, I encountered this error: "ld: library not found for -lSystem" on macOS 10.15.5 and have no idea to fix it.
