### ISSUE TITLE
Can't install to WSL

### ISSUE THREAD

**Issue by sasagawa888** [zeam-vm/pelemay#23]
I got following message.

mix deps.get

12:50:53.498 [error] Unable to load crypto library. Failed with error:
":load_failed, Failed to load NIF library: '/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1
_1_1' not found (required by /usr/lib/erlang/lib/crypto-4.5.1/priv/lib/crypto.so)'"
OpenSSL might not be installed on this system.

I updated Elixir by ASDF 
asdf list
elixir
  1.9.0
erlang
No versions installed

My environment is following.
Windows subsystem for LInux
Ubuntu 18.04

**Comment by zacky1972** [comment]
I'm sorry but we haven't tested Pelemay on a WSL environment, yet. It requires some much times.

If you harry up to use Pelemay. try it on Mac.

We're trying to test it on Linux, soon, though we'll try to do so on WSL, later.

**Comment by zacky1972** [comment]
@sasagawa888 

I guess that the following error indicates that installing Erlang is not completed.

```
12:50:53.498 [error] Unable to load crypto library. Failed with error:
":load_failed, Failed to load NIF library: '/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1
_1_1' not found (required by /usr/lib/erlang/lib/crypto-4.5.1/priv/lib/crypto.so)'"
OpenSSL might not be installed on this system.

I updated Elixir by ASDF
asdf list
elixir
1.9.0
erlang
No versions installed
```

Would you install OpenSSL and the latest Erlang?

I don't know how to install OpenSSL on WSL.

To install the current latest Erlang: `asdf install erlang 22.0.7`

**Comment by zacky1972** [comment]
Perhaps it is the same issue to #52
