### ISSUE TITLE
Not found basic.c when installed from Hex

### ISSUE THREAD

**Issue by muramasa8191** [zeam-vm/pelemay#24]
## Problem detail
When we write the `defpelemay` in our own projects, the generator try to read basic.c in deps/pelemay/lib/pelemay/generator/native. However, the path as `dir` attribute points just from the library, "lib/pelemay/generator/native/". It results file not found.

## Suggestion
When the file is not found, add the path for dependency, "deps/pelemay/".

**Comment by zacky1972** [comment]
The temporary fixed PR is #31 

I believe this issue will be fixed by #31 and #28
