### ISSUE TITLE
The functional testing is not passed in the PR #38

### ISSUE THREAD

**Issue by zacky1972** [zeam-vm/pelemay#39]
**Describe the bug**
When applying the PR #38, the functional testing is not passed.

**To Reproduce**
1. Pull the PR #38 
2. Do `mix test`
3. See error

```
$ mix test
make: Nothing to be done for `all'.


  1) test Basic functional testing for Pelemay (PelemayTest)
     test/pelemay_test.exs:5
     ** (UndefinedFunctionError) function PelemayTest.Sample.map_square/1 is undefined (module PelemayTest.Sample is not available)
     code: result = 1..4 |> Enum.to_list |> PelemayTest.Sample.map_square
     stacktrace:
       PelemayTest.Sample.map_square([1, 2, 3, 4])
       test/pelemay_test.exs:6: (test)


20:47:28.204 [warn]  The on_load function for module Elixir.PelemayNif returned:
{:error, {:load_failed, 'Failed to load NIF library: \'dlopen(/Users/zacky/github/pelemay/_build/test/lib/pelemay/priv/libnif.so, 2): image not found\''}}

...........warning: PelemayNifElixirPelemayTestSample.map_mult/1 is undefined (module PelemayNifElixirPelemayTestSample is not available or is yet to be defined)
  test/pelemay_test.exs:15: PelemayTest.Sample.map_square/1
```

There aren't generate code completely in the building directory: 

```
$ ls _build/test/lib/pelemay/priv/
generated.mk
pelemay_nif_elixir_pelemaytest_sample.ex
```

The target in the generated `generated.mk` is empty:

```
$ cat _build/test/lib/pelemay/priv/generated.mk 
# This file was generated by Pelemay.Generator.Makefile
TARGET_LIBS :=
```

**Expected behavior**

`ls` in the building directory should be as follows: 

```
$ ls _build/test/lib/pelemay/priv/
generated.mk
pelemay_nif_elixir_pelemaytest_sample.ex
libelixirpelemaytestsample.c
libelixirpelemaytestsample.so
```

The target in the generated `generated.mk` should be as follows:

```
$ cat _build/test/lib/pelemay/priv/generated.mk 
# This file was generated by Pelemay.Generator.Makefile
TARGET_LIBS := libelixirpelemaytestsample.so
```

And then, the functional testing will be passed successfully.

**Screenshots**
omitted

**Desktop (please complete the following information):**
 - Elixir & Erlang/OTP versions (`elixir --version`):

```
$ elixir -v
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.10.0-dev (587453b) (compiled with Erlang/OTP 22)
```

```
$ elixir -v
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 22)
```

 - OS: 

macOS Mojave 10.14.6

 - Version: 

master

**Additional context**

I guess Pelemay doesn't work well in test directory.

**Comment by zacky1972** [comment]
@muramasa8191 said:

> プログラミングElixirをちょうど読み返してたらquoteの辺りでExUnitに言及があったのですが、testマクロではquoteが生成されて、的な話で、compileの対象にはならない気がします。ちょっとtestのコード見れてませんが。

> I read the book of Programming Elixir again, and found a mention to ExUnit and `quote`. I guess it may not be a target of compiling because `quote` may be generated (and inactive) in a test macro, though I didn't see the code of the test macro.

> https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/case.ex

**Comment by zacky1972** [comment]
I guess the macro of Pelemay may be inactive in the test code.

Is it true? @josevalim

**Comment by josevalim** [comment]
Macros should work fine on test. But the issue is that, if Pelemey depends on some Mix task or on the compiler, those hooks may not run, because test files are not written to disk.

You can fix this by putting the fixtures in test/support and changing your mix.exs to do this:

    elixirc_paths: elixirc_paths(Mix.env())

where:

    defp elixirc_paths(:test), do: ["lib", "test/support"]
    defp elixirc_paths(_), do: ["lib"]

**Comment by zacky1972** [comment]
Thank you @josevalim ! I've fixed it!
