### ISSUE TITLE
Sample Project using Pelemay doesn't work on Windows

### ISSUE THREAD

**Issue by piacerex** [zeam-vm/pelemay#52]
**Describe the bug**
Sample Project using Pelemay doesn't work on Windows
(Since this phenomenon doesn't occur in mac, it's bug assumed specific to Windows)

**To Reproduce**
1. Use Pelemay in the source code 
Source codes and commands are written in following column
https://qiita.com/piacerex/items/b6f12682038975d59119

2. Run in the command:
```
iex -S mix
iex> PelemaySample.map_square [ 1, 2, 3 ]
```
3. See error
```
** (ArgumentError) argument error
    (stdlib) :io.put_chars(:standard_io, :unicode, [<<32, 32, 32, 131, 137, 131, 67, 131, 117, 131, 137, 131, 138, 32, 99, 58, 47, 112, 105, 97, 99, 101, 114, 101, 47, 99, 111, 100, 101, 47, 112, 101, 108, 101, 109, 97, 121, 95, 115, 97, 109, 112, 108, 101, 47, 95, 98, 117, 105, ...>>, 10])
    lib/pelemay.ex:53: Pelemay.pelemaystub/2
    expanding macro: Pelemay.defpelemay/1
    lib/pelemay_sample.ex:5: PelemaySample (module)
```

**Expected behavior**
```
iex> PelemaySample.map_square [ 1, 2, 3 ]
[ 1, 4, 9 ]
```

**Screenshots**
See following column
https://qiita.com/piacerex/items/b6f12682038975d59119

**Desktop (please complete the following information):**
Below is my desktop version on Windows:

- Pelemay Version: 0.0.2
- Elixir & Erlang/OTP versions (elixir --version):
```
> elixir --version
Erlang/OTP 20 [erts-9.0] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10]

Elixir 1.9.1 (compiled with Erlang/OTP 20)
```
- OS (OS name & version, and On Windows, use ver instead of uname):
```
> ver
Microsoft Windows [Version 10.0.17134.1006]
```

- Clang versions (clang -v):
```
clang version 8.0.0 (tags/RELEASE_800/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Tools\LLVM\bin
```

**Additional context**
This details are discussed in the comments section in following column (but in japanese)
https://qiita.com/piacerex/items/b6f12682038975d59119

**Comment by zacky1972** [comment]
Would you execute the following Elixir script?

```
iex> :os.type()
```

**Comment by piacerex** [comment]
```
iex> :os.type()
{:win32, :nt}
```

Please add you this instruction on "Bug report issue template"

**Comment by zacky1972** [comment]
> Please add you this instruction on "Bug report issue template"

I agree it.

**Comment by piacerex** [comment]
This issue has been provisionally resolved

**Procedure**
Renaming to ``libnifelixirpelemaysample.dll`` from ``libnifelixirpelemaysample.so`` in ``_build/dev/lib/pelemay/priv/``

**Results**
```
iex -S mix
iex> PelemaySample.map_square [ 1, 2, 3 ]
[1, 4, 9]
```

**Comment by zacky1972** [comment]
Thank you, @piacerex 

I'll revise Pelemay.Generator.Builder to fix this issue.

**Comment by zacky1972** [comment]
After `mix clean` and `mix deps.clean --all`,

Try the following fragment of `mix.exs`:

```
  defp deps do
    [
      {:pelemay, git: "https://github.com/zeam-vm/pelemay.git", branch: "zacky1972_issue_52"},
    ]
  end
```

**Comment by piacerex** [comment]
Verification succeeded, fix was no problem :-)
