### ISSUE TITLE
mix test invoked error

### ISSUE THREAD

**Issue by sasagawa888** [zeam-vm/pelemay#6]
I made a Pelery clone.
And I updated Elixir to 1.9.0.
I ran mix test. I got following results:
== Compilation error in file test/hastega/generator_test.exs ==
** (CompileError) test/hastega/generator_test.exs:3: module Hastega.Generator is not loaded and could not
be found

**Comment by pdgonzalez872** [comment]
I think https://github.com/zeam-vm/pelemay/pull/5 should fix this issue.

**Comment by zacky1972** [comment]
Thank you, @sasagawa888 and @pdgonzalez872

**Comment by zacky1972** [comment]
I confirmed #6 is fixed by #5
