### ISSUE TITLE
Description of the top of the API Reference is incomplete

### ISSUE THREAD

**Issue by zacky1972** [zeam-vm/pelemay#62]
**Describe the bug**
Description in README.md includes sample code, though that of the top of the API Reference in HexDocs ( https://hexdocs.pm/pelemay/0.0.3/api-reference.html ) don't so.

**To Reproduce**
None.

**Expected behavior**
Description of the top of the API Reference should include sample code.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - Pelemay Version: 0.0.3

**Additional context**
It is necessary to ask details of the specification of ExDoc and HexDocs to someone who understand it enough to explain it to us.

**Comment by supersimple** [comment]
@zacky1972 The API reference is supposed to be an abbreviated version of each moduledoc.
If you would prefer not to have the api-reference page generated, you can set the option `api_reference: false` in your doc configs.

You can see an example here:
https://hexdocs.pm/jason/api-reference.html#content
where the content has been abbreviated from:
https://hexdocs.pm/jason/Jason.Encoder.html

**Comment by zacky1972** [comment]
Thank you for your advices @supersimple !!!

I'll try it.
